# Generated by Django 3.1.4 on 2020-12-22 04:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Employeeincomestatement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personeis',
            name='IDcard',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='身份证'),
        ),
        migrations.AlterField(
            model_name='personeis',
            name='account',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='工号'),
        ),
        migrations.AlterField(
            model_name='personeis',
            name='comments',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='personeis',
            name='month_end',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='终止月'),
        ),
        migrations.AlterField(
            model_name='personeis',
            name='month_salary',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='月平均工资'),
        ),
        migrations.AlterField(
            model_name='personeis',
            name='month_start',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='起始月'),
        ),
        migrations.AlterField(
            model_name='personeis',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='姓名'),
        ),
        migrations.AlterField(
            model_name='personeis',
            name='signature',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='本人签字'),
        ),
        migrations.AlterField(
            model_name='personeis',
            name='sum_salary',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='年工资总额'),
        ),
    ]
