# Generated by Django 3.1.4 on 2020-12-30 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employeeincomestatement', '0004_auto_20201223_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personeis',
            name='comments',
            field=models.CharField(blank=True, default=' ', max_length=200, null=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='personeis',
            name='signature',
            field=models.CharField(blank=True, default=' ', max_length=200, null=True, verbose_name='本人签字'),
        ),
    ]
