# Generated by Django 3.1.4 on 2020-12-31 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Employeeincomestatement', '0005_auto_20201230_1043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personeis',
            name='IDcard',
        ),
    ]
