# Generated by Django 3.1.4 on 2021-01-03 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employeeincomestatement', '0006_remove_personeis_idcard'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadExcel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='', verbose_name='上传Excel')),
                ('check_people', models.BooleanField(default=False, verbose_name='检查谁没有注册')),
            ],
            options={
                'verbose_name': '上传职工收入对账单Excel',
                'verbose_name_plural': '上传职工收入对账单Excel',
            },
        ),
    ]
