# Generated by Django 3.1.4 on 2020-12-16 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('pwd', models.CharField(max_length=200)),
                ('IDcard', models.IntegerField()),
                ('gongjijinzhanghao', models.IntegerField()),
                ('accumulated_account_balance', models.FloatField()),
                ('cumulative_balance', models.FloatField()),
                ('qi_bu_cumulative_balance', models.FloatField()),
                ('balance_at_the_end_of_the_previous_year', models.FloatField()),
                ('qi_ye_at_the_end_of_the_previous_year', models.FloatField()),
                ('interest_paid_at_the_end_of_the_previous_year', models.FloatField()),
                ('qi_ye_interest_paid_at_the_end_of_the_previous_year', models.FloatField()),
                ('amount_paid_this_year', models.FloatField()),
                ('the_amount_of_enterprise_compensation_this_year', models.FloatField()),
                ('interest_paid_this_year', models.FloatField()),
                ('this_years_corporate_interest', models.FloatField()),
                ('interest_rate_this_year', models.FloatField()),
                ('last_year_interest_rate', models.FloatField()),
                ('this_year_get_money', models.FloatField()),
                ('withdrawal_date_this_year', models.FloatField()),
                ('content', models.TextField()),
            ],
        ),
    ]
