# Generated by Django 3.1.4 on 2020-12-17 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HousingProvidenFundStatement', '0002_auto_20201216_1645'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadexcel',
            name='name',
        ),
        migrations.AlterField(
            model_name='uploadexcel',
            name='file',
            field=models.FileField(upload_to=''),
        ),
    ]
