# Generated by Django 3.1.4 on 2020-12-19 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HousingProvidenFundStatement', '0004_auto_20201219_1250'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadexcel',
            name='filename',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
