# Generated by Django 3.1.4 on 2020-12-20 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HousingProvidenFundStatement', '0005_uploadexcel_filename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='accumulated_account_balance',
            field=models.CharField(max_length=200, verbose_name='账号累计余额'),
        ),
        migrations.AlterField(
            model_name='person',
            name='amount_paid_this_year',
            field=models.CharField(max_length=200, verbose_name='本年个缴金额'),
        ),
        migrations.AlterField(
            model_name='person',
            name='balance_at_the_end_of_the_previous_year',
            field=models.CharField(max_length=200, verbose_name='上年末个缴余额'),
        ),
        migrations.AlterField(
            model_name='person',
            name='cumulative_balance',
            field=models.CharField(max_length=200, verbose_name='个缴累计余额'),
        ),
        migrations.AlterField(
            model_name='person',
            name='gongjijinzhanghao',
            field=models.CharField(max_length=200, verbose_name='公积金账号'),
        ),
        migrations.AlterField(
            model_name='person',
            name='interest_paid_at_the_end_of_the_previous_year',
            field=models.CharField(max_length=200, verbose_name='上年末个缴利息'),
        ),
        migrations.AlterField(
            model_name='person',
            name='interest_paid_this_year',
            field=models.CharField(max_length=200, verbose_name='本年个缴利息'),
        ),
        migrations.AlterField(
            model_name='person',
            name='interest_rate_this_year',
            field=models.CharField(max_length=200, verbose_name='本年利率'),
        ),
        migrations.AlterField(
            model_name='person',
            name='last_year_interest_rate',
            field=models.CharField(max_length=200, verbose_name='上年利率'),
        ),
        migrations.AlterField(
            model_name='person',
            name='qi_bu_cumulative_balance',
            field=models.CharField(max_length=200, verbose_name='企补累计余额'),
        ),
        migrations.AlterField(
            model_name='person',
            name='qi_ye_at_the_end_of_the_previous_year',
            field=models.CharField(max_length=200, verbose_name='上年末企补余额'),
        ),
        migrations.AlterField(
            model_name='person',
            name='qi_ye_interest_paid_at_the_end_of_the_previous_year',
            field=models.CharField(max_length=200, verbose_name='上年末企补利息'),
        ),
        migrations.AlterField(
            model_name='person',
            name='the_amount_of_enterprise_compensation_this_year',
            field=models.CharField(max_length=200, verbose_name='本年企补金额'),
        ),
        migrations.AlterField(
            model_name='person',
            name='this_year_get_money',
            field=models.CharField(max_length=200, verbose_name='本年提取金额'),
        ),
        migrations.AlterField(
            model_name='person',
            name='this_years_corporate_interest',
            field=models.CharField(max_length=200, verbose_name='本年企补利息'),
        ),
        migrations.AlterField(
            model_name='person',
            name='withdrawal_date_this_year',
            field=models.CharField(max_length=200, verbose_name='本年提取日期'),
        ),
    ]
