# Generated by Django 3.1.4 on 2020-12-22 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HousingProvidenFundStatement', '0009_auto_20201222_0742'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='IDcard',
        ),
    ]
