# Generated by Django 3.1.4 on 2020-12-22 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HousingProvidenFundStatement', '0010_remove_person_idcard'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='name',
            new_name='personname',
        ),
    ]
