# Generated by Django 3.1.4 on 2020-12-22 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HousingProvidenFundStatement', '0011_auto_20201222_0940'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='personname',
            new_name='user',
        ),
    ]
