# Generated by Django 3.1.4 on 2020-12-22 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HousingProvidenFundStatement', '0012_auto_20201222_1003'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='name',
            field=models.CharField(default='许智豪', max_length=200, verbose_name='姓名'),
            preserve_default=False,
        ),
    ]
