# Generated by Django 3.1.4 on 2020-12-23 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HousingProvidenFundStatement', '0014_auto_20201223_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='deposit_month',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='缴存月份'),
        ),
    ]
