# Generated by Django 3.1.4 on 2020-12-31 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HousingProvidenFundStatement', '0016_auto_20201230_1043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='user',
        ),
        migrations.AddField(
            model_name='person',
            name='IDcard',
            field=models.CharField(default=2, max_length=200, verbose_name='身份证'),
            preserve_default=False,
        ),
    ]
