# Generated by Django 3.1.4 on 2021-01-03 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HousingProvidenFundStatement', '0017_auto_20201231_1039'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='uploadexcel',
            options={'verbose_name': '上传住房公积金对账单Excel', 'verbose_name_plural': '上传住房公积金对账单Excel'},
        ),
        migrations.RemoveField(
            model_name='uploadexcel',
            name='filename',
        ),
        migrations.AlterField(
            model_name='uploadexcel',
            name='file',
            field=models.FileField(upload_to='', verbose_name='上传Excel'),
        ),
    ]
