# Generated by Django 3.1.4 on 2021-01-03 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HousingProvidenFundStatement', '0018_auto_20210103_1750'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadexcel',
            name='check_people',
            field=models.BooleanField(default=False, verbose_name='检查谁没有注册'),
        ),
    ]
