# Generated by Django 3.1.4 on 2021-01-03 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HousingProvidenFundStatement', '0019_uploadexcel_check_people'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Upload_User',
        ),
    ]
