# Generated by Django 3.1.4 on 2021-02-09 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HousingProvidenFundStatement', '0020_delete_upload_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='havelook',
            field=models.CharField(blank=True, default='否', max_length=100, null=True, verbose_name='是否查看'),
        ),
    ]
